-- 插入最近7天的测试数据，确保图表能显示数据

-- 插入最近7天的考试结果数据
INSERT INTO exam_result (user_id, paper_id, total_score, start_time, end_time, duration, paper_difficulty) VALUES
-- 今天的数据
(1, 1, 85.5, DATE_SUB(NOW(), INTERVAL 0 DAY), DATE_SUB(NOW(), INTERVAL 0 DAY), 1800, 'EASY'),
(2, 2, 92.0, DATE_SUB(NOW(), INTERVAL 0 DAY), DATE_SUB(NOW(), INTERVAL 0 DAY), 2100, 'MEDIUM'),
(3, 3, 78.5, DATE_SUB(NOW(), INTERVAL 0 DAY), DATE_SUB(NOW(), INTERVAL 0 DAY), 2400, 'HARD'),

-- 昨天的数据
(4, 1, 88.0, DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_SUB(NOW(), INTERVAL 1 DAY), 1900, 'EASY'),
(5, 2, 76.5, DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_SUB(NOW(), INTERVAL 1 DAY), 2200, 'MEDIUM'),
(6, 3, 82.0, DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_SUB(NOW(), INTERVAL 1 DAY), 2300, 'HARD'),
(7, 1, 91.5, DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_SUB(NOW(), INTERVAL 1 DAY), 1700, 'EASY'),

-- 2天前的数据
(8, 2, 79.0, DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY), 2000, 'MEDIUM'),
(9, 3, 85.5, DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY), 2500, 'HARD'),
(10, 1, 87.5, DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY), 1800, 'EASY'),
(1, 2, 93.0, DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY), 2100, 'MEDIUM'),

-- 3天前的数据
(2, 3, 81.0, DATE_SUB(NOW(), INTERVAL 3 DAY), DATE_SUB(NOW(), INTERVAL 3 DAY), 2400, 'HARD'),
(3, 1, 89.5, DATE_SUB(NOW(), INTERVAL 3 DAY), DATE_SUB(NOW(), INTERVAL 3 DAY), 1900, 'EASY'),
(4, 2, 77.5, DATE_SUB(NOW(), INTERVAL 3 DAY), DATE_SUB(NOW(), INTERVAL 3 DAY), 2200, 'MEDIUM'),

-- 4天前的数据
(5, 3, 84.0, DATE_SUB(NOW(), INTERVAL 4 DAY), DATE_SUB(NOW(), INTERVAL 4 DAY), 2300, 'HARD'),
(6, 1, 90.0, DATE_SUB(NOW(), INTERVAL 4 DAY), DATE_SUB(NOW(), INTERVAL 4 DAY), 1700, 'EASY'),
(7, 2, 75.5, DATE_SUB(NOW(), INTERVAL 4 DAY), DATE_SUB(NOW(), INTERVAL 4 DAY), 2000, 'MEDIUM'),
(8, 3, 86.5, DATE_SUB(NOW(), INTERVAL 4 DAY), DATE_SUB(NOW(), INTERVAL 4 DAY), 2500, 'HARD'),

-- 5天前的数据
(9, 1, 88.5, DATE_SUB(NOW(), INTERVAL 5 DAY), DATE_SUB(NOW(), INTERVAL 5 DAY), 1800, 'EASY'),
(10, 2, 80.0, DATE_SUB(NOW(), INTERVAL 5 DAY), DATE_SUB(NOW(), INTERVAL 5 DAY), 2100, 'MEDIUM'),
(1, 3, 83.5, DATE_SUB(NOW(), INTERVAL 5 DAY), DATE_SUB(NOW(), INTERVAL 5 DAY), 2400, 'HARD'),

-- 6天前的数据
(2, 1, 91.0, DATE_SUB(NOW(), INTERVAL 6 DAY), DATE_SUB(NOW(), INTERVAL 6 DAY), 1900, 'EASY'),
(3, 2, 78.0, DATE_SUB(NOW(), INTERVAL 6 DAY), DATE_SUB(NOW(), INTERVAL 6 DAY), 2200, 'MEDIUM'),
(4, 3, 85.0, DATE_SUB(NOW(), INTERVAL 6 DAY), DATE_SUB(NOW(), INTERVAL 6 DAY), 2300, 'HARD');

-- 插入最近7天的答题数据（用于柱状图）
INSERT INTO exam_answer (user_id, question_id, user_answer, is_correct, answer_time) VALUES
-- 今天的答题数据
(1, 1, 'A', 1, DATE_SUB(NOW(), INTERVAL 0 DAY)),
(1, 2, 'B,C', 1, DATE_SUB(NOW(), INTERVAL 0 DAY)),
(1, 3, '这是简答题答案', 1, DATE_SUB(NOW(), INTERVAL 0 DAY)),
(1, 4, '填空答案', 0, DATE_SUB(NOW(), INTERVAL 0 DAY)),
(1, 5, 'true', 1, DATE_SUB(NOW(), INTERVAL 0 DAY)),

-- 昨天的答题数据
(2, 1, 'A', 1, DATE_SUB(NOW(), INTERVAL 1 DAY)),
(2, 2, 'A,B', 0, DATE_SUB(NOW(), INTERVAL 1 DAY)),
(2, 3, '简答题回答', 1, DATE_SUB(NOW(), INTERVAL 1 DAY)),
(2, 4, '填空内容', 1, DATE_SUB(NOW(), INTERVAL 1 DAY)),
(2, 5, 'false', 0, DATE_SUB(NOW(), INTERVAL 1 DAY)),

(3, 1, 'B', 0, DATE_SUB(NOW(), INTERVAL 1 DAY)),
(3, 2, 'B,C', 1, DATE_SUB(NOW(), INTERVAL 1 DAY)),
(3, 3, '另一个简答', 0, DATE_SUB(NOW(), INTERVAL 1 DAY)),
(3, 4, '填空回答', 1, DATE_SUB(NOW(), INTERVAL 1 DAY)),
(3, 5, 'true', 1, DATE_SUB(NOW(), INTERVAL 1 DAY)),

-- 2天前的答题数据
(4, 1, 'A', 1, DATE_SUB(NOW(), INTERVAL 2 DAY)),
(4, 2, 'A,C', 0, DATE_SUB(NOW(), INTERVAL 2 DAY)),
(4, 3, '简答内容', 1, DATE_SUB(NOW(), INTERVAL 2 DAY)),
(4, 4, '填空答案', 1, DATE_SUB(NOW(), INTERVAL 2 DAY)),
(4, 5, 'true', 1, DATE_SUB(NOW(), INTERVAL 2 DAY)),

(5, 1, 'C', 0, DATE_SUB(NOW(), INTERVAL 2 DAY)),
(5, 2, 'B,C', 1, DATE_SUB(NOW(), INTERVAL 2 DAY)),
(5, 3, '简答回复', 0, DATE_SUB(NOW(), INTERVAL 2 DAY)),
(5, 4, '填空内容', 0, DATE_SUB(NOW(), INTERVAL 2 DAY)),
(5, 5, 'false', 1, DATE_SUB(NOW(), INTERVAL 2 DAY)),

-- 3天前的答题数据
(6, 1, 'A', 1, DATE_SUB(NOW(), INTERVAL 3 DAY)),
(6, 2, 'A,B', 1, DATE_SUB(NOW(), INTERVAL 3 DAY)),
(6, 3, '简答题目', 1, DATE_SUB(NOW(), INTERVAL 3 DAY)),
(6, 4, '填空题目', 1, DATE_SUB(NOW(), INTERVAL 3 DAY)),
(6, 5, 'true', 0, DATE_SUB(NOW(), INTERVAL 3 DAY)),

-- 4天前的答题数据
(7, 1, 'B', 0, DATE_SUB(NOW(), INTERVAL 4 DAY)),
(7, 2, 'B,C', 1, DATE_SUB(NOW(), INTERVAL 4 DAY)),
(7, 3, '简答解答', 1, DATE_SUB(NOW(), INTERVAL 4 DAY)),
(7, 4, '填空解答', 0, DATE_SUB(NOW(), INTERVAL 4 DAY)),
(7, 5, 'false', 1, DATE_SUB(NOW(), INTERVAL 4 DAY)),

-- 5天前的答题数据
(8, 1, 'A', 1, DATE_SUB(NOW(), INTERVAL 5 DAY)),
(8, 2, 'A,C', 0, DATE_SUB(NOW(), INTERVAL 5 DAY)),
(8, 3, '简答内容', 0, DATE_SUB(NOW(), INTERVAL 5 DAY)),
(8, 4, '填空内容', 1, DATE_SUB(NOW(), INTERVAL 5 DAY)),
(8, 5, 'true', 1, DATE_SUB(NOW(), INTERVAL 5 DAY)),

-- 6天前的答题数据
(9, 1, 'A', 1, DATE_SUB(NOW(), INTERVAL 6 DAY)),
(9, 2, 'B,C', 1, DATE_SUB(NOW(), INTERVAL 6 DAY)),
(9, 3, '简答回答', 1, DATE_SUB(NOW(), INTERVAL 6 DAY)),
(9, 4, '填空回答', 1, DATE_SUB(NOW(), INTERVAL 6 DAY)),
(9, 5, 'false', 0, DATE_SUB(NOW(), INTERVAL 6 DAY));